title: Xiangwei Wang's Homepage
page-top-title: Xiangwei Wang
top-section-bg-text: Computer Science
home-subtitle: Xiangwei Wang&ensp;|&ensp;王祥伟
copyright-text: '&copy; Xiangwei Wang 2025. All Rights Reserved.'
